let cards = [
	{	text: "HAS"						},
	{	text: "AS"						},
	{	text: "WAS"						},
	{	text: "AGAIN"					},
	{	text: "BLUE"					},
	{	text: "YELLOW"					},
	{	text: "RED"						},
	{	text: "GREEN"					},
	{	text: "PURPLE"					},
	{	text: "ORANGE"					},
	{	text: "WALK"					},
	{	text: "JUST"					},
	{	text: "KNOW"					},
	{	text: "WERE"					},
	{	text: "THEN"					},
	{	text: "THINK"					},
	{	text: "WHEN"					},
	{	text: "ALIVE"					},
	{	text: "MAY"						},
	{	text: "OF"						},
	{	text: "SOME"					},
	{	text: "STOP"					},
	{	text: "TAKE"					},
	{	text: "AN"						},
	{	text: "ANY"						},
	{	text: "EVERY "					},
	{	text: "FLY"						},
	{	text: "FROM"					},
	{	text: "HER"						},
	{	text: "HIM"						},
	{	text: "OLD"						},
	{	text: "ONCE"					},
	{	text: "OPEN"					},
	{	text: "THANK"					},
	{	text: "THEM"					},
	{	text: "ASK"						},
	{	text: "GIVE"					},
	{	text: "BY"						},
	{	text: "COULD"					},
	{	text: "HIS"						},
	{	text: "GOING"					},
	{	text: "HAD"						},
	{	text: "OVER"					},
	{	text: "HOW"						},
	{	text: "LET"						},
	{	text: "PUT"						},
	{	text: "ROUND"					},
	{	text: "HOP ON POP",				},
	{	text: "JUMP ON POP",			},
	{	text: "KICK THE CAT",			},
	{	text: "STEP ON THE CAT",		},
	{	text: "RUB THE DOG",			},
	{	text: "PET THE DOG",			},
	{	text: "SMELL THE DOG",			},
	{	text: "THE DOG IS SMELLING ME",	},
	{	text: "THE DOG IS SMELLY",		},
	{	text: "AS"						},
];
