let cards = [
    { text: "Once upon a time, in a big city," },
    { text: "There was a young inventor named Lucy." },
    { text: "She had a messy workshop with cool gadgets." },
    { text: "One rainy day, Lucy put on her special lab coat and glasses." },
    { text: "In her workshop, she had a talking parrot named Polly." },
    { text: "Polly told Lucy about a magical time-travel machine." },
    { text: "Lucy said thank you to Polly and started working." },
    { text: "She used tools to make it just right." },
    { text: "Then, she turned on the time machine." },
    { text: "It made lots of noise and bright lights." },
    { text: "Suddenly, Lucy was in a place that looked like a fairy tale." },
    { text: "She saw knights and castles in a kingdom." },
    { text: "But, a dragon was causing trouble!" },
    { text: "Lucy knew she had to help." },
    { text: "She made a special suit and a water cannon." },
    { text: "Lucy bravely faced the dragon and saved the kingdom." },
    { text: "People in the kingdom were so happy." },
    { text: "Lucy went back to her time using the machine." },
    { text: "Polly, the parrot, was waiting for her." },
    { text: "They shared stories of their amazing adventure." },
    { text: "Lucy kept inventing and making the world better." },
    { text: "And that's how Lucy became a legend!" },
];
